<?php
/*$host="ap-cdbr-azure-southeast-b.cloudapp.net"
$username="b9dcff53f2848f";
$password="0af59698";
$database="Waste";*/
$host="localhost";
$username="root";
$password="root";
$database="waste";
?>